### PR TITLE
Change minimize to a boolean flag with an option minimize-length argument

### PR DESCRIPTION
**Pull request by dgubitosi**
## What does this PR do?
Changes the --minimize option to a boolean flag.  The default is --no-minimize and does not need to be supplied on the command line.  When --minimize is supplied, the default character length is zero.  An optional --minimize-length option can be used to override and only accepts integers >= 0.

[//]: # (Required: Describe the effects of your pull request in detail. If multiple changes are involved, a bulleted list is often useful.)
- Changes --minimize to a boolean flag.  Unfortunately, this breaks compatibility.

## What gif best describes this PR or how it makes you feel?
N/A

[//]: # (Encouraged: Insert an appropriate gif/meme to brighten up your reviewer's day.)

## Completion checklist

- [ ] CHANGELOG.md has been updated to reflect the changes
- [ ] Additions and changes have unit tests
- [ ] [Unit tests, Pylint, security testing, and Integration tests are passing.](https://github.com/salesforce/policy_sentry/actions). GitHub actions does this automatically
- [ ] The pull request has been appropriately labeled using the provided PR labels

### CODE REVIEW

**Comment by dgubitosi** [comment]
@kmcquade This is what we discussed in the other PR.  Let me know what you think.  I'm going to give some though on how this might be done without breaking backward compatibility.

**Comment by dgubitosi** [comment]
I've been playing with terraform and I found a way to remove the need for the extraneous --no-minimize by constructing the program[] list with a condition and concat().  I'm still researching if there's any way to maintain backward compatibility with --minimize {value}

**Comment by kmcquade** [comment]
@dgubitosi I am okay with breaking the backward compatibility here. Can you change the version in policy_sentry/bin/cli.py to 0.10.0? We'll make sure it shows up with breaking changes

**Comment by reetasingh** [comment]
> @dgubitosi I am okay with breaking the backward compatibility here. Can you change the version in policy_sentry/bin/cli.py to 0.10.0? We'll make sure it shows up in the release notes with breaking changes

@kmcquade We can also label the PR with minor label and the release notes will be updated https://github.com/salesforce/policy_sentry/blob/54066aa7237b7c383f78bf98787a79369dd1048e/.github/release-drafter.yml#L27

**Comment by kmcquade** [comment]
@reetasingh - @dgubitosi  will still need to update the `cli.py` file, and then for us to tag the release on the git side, we use the release drafter.

**Comment by reetasingh** [comment]
> @reetasingh - @dgubitosi will still need to update the `cli.py` file, and then for us to tag the release on the git side, we use the release drafter.
yes

**Comment by dgubitosi** [comment]
I managed to maintain backward compatibility.

policy_sentry write-policy --input-file foo.yaml  => does not minimize
policy_sentry write-policy --input-file foo.yaml --minimize => acts like a simple flag that does greedy minimize
policy_sentry write-policy --input-file foo.yaml --minimize 0 => like before will greedy minimize
policy_sentry write-policy --input-file foo.yaml --minimize 5 => like before will minimize to 5 characters

And I removed the extraneous --no-minimize flag since I can work around it in terraform.

**Comment by kmcquade** [comment]
Fantastic! @dgubitosi if this is in the final state, let me know and we can merge

**Comment by dgubitosi** [comment]
Hmm.  I've been doing some more experimentation with click.  I thought is_eager on the flag helps enforce that the argument had to follow it, but that's not the case.  It works the same without it, and in reality I'm just abusing an argument to mimic the previous command line behavior.  

For example, these two commands are identical:

policy_sentry write-policy --input-file foo.yaml --minimize 5
policy_sentry write-policy 5 --minimze --input-file foo.yaml

Similarly these two commands are identical and valid as side-effect of my argument abuse:

policy_sentry write-policy --input-file foo.yaml 5
policy_sentry write-policy 5 --input-file foo.yaml

Click captures the numeric argument where ever it is on the command, and irregardless if the --minimize flag is present.  However, the argument value has no purpose unless its accompanied by the --minimize flag.  The code ignores it otherwise.

Do you think this is an issue?

**Comment by kmcquade** [comment]
Hmmm. I'm not sure about this one. It's kind of like a bug by design lol. @reetasingh what do you think about this one? I could use your opinion.

**Comment by dgubitosi** [comment]
I didn't like the argument abuse so I found the proper solution.  As you can see, the code is more complicated as it required using custom classes and a custom parser to overcome this limitation of click.  The solution uses a "hidden" option, --minimize_length, and a special attribute attached to --minimize that is used in the parser.  The parser looks for all options with the special attribute, and processes them uniquely.  In this case, when the parser encounters --minimize on the arguments list, it checks to see if there's an argument following it.  If so, it moves that argument into the hidden --minimize_length option.  This ensures that the command line is in the correct order.

All of these are valid and identical:
policy_sentry write-policy --input-file foo.yaml --minimize
policy_sentry write-policy --input-file foo.yaml --minimize 5
policy_sentry write-policy --input-file foo.yaml --minimize=5
policy_sentry write-policy --minimize 5 --input-file foo.yaml
policy_sentry write-policy --minimize=5 --input-file foo.yaml

These are now invalid as the 5 is a stray argument:
policy_sentry write-policy --input-file foo.yaml 5
policy_sentry write-policy --minimize --input-file foo.yaml 5

Technically, these are also valid as the hidden option can be supplied on the command line:
policy_sentry write-policy --input-file foo.yaml --minimize --minimize_length=5
policy_sentry write-policy --input-file foo.yaml --minimize_length 5 --minimize

And this leads in a side effect as this is also valid:
policy_sentry write-policy --input-file foo.yaml --minimize_length=5 --minimize=0

This gets expanded by the custom parser into this:
policy_sentry write-policy --input-file foo.yaml --minimize_length=5 --minimize --minimize_length=0

When this is encountered, the value of the last instance of --minimize_length is used

**Comment by dgubitosi** [comment]
I'll take a look at addressing those pylint checks.

**Comment by kmcquade** [comment]
Fantastic! Sure. When those are fixed I'll go ahead and merge.

Really appreciate the contribution here.

**Review by kmcquade — APPROVED** [review]

**Comment by dgubitosi** [comment]
I incremented the version in cli.py to 0.10.0 as discussed.  I will start on a PR for terraform-aws-policy-sentry so it conforms to this new version.

**Pull request merged**
