### PR TITLE
feat: expand capability of '*' querying action table

### PR DESCRIPTION
**Pull request by Scribbd**
## What does this PR do?

This change expands the capability of using `policy_sentry query action-table -s [service] -n "*"` to also be able to filter based on a prefix. Example:

```
policy_sentry query action-table -s s3 -n "GetObject*"                                                                                                            21:20:33
{
    "s3": [
        {
            "action": "s3:GetObject",
            "description": "Grants permission to retrieve objects from Amazon S3",
            "access_level": "Read",
            "api_documentation_link": "https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html",
            "resource_arn_format": "arn:${Partition}:s3:::${BucketName}/${ObjectName}",
            "condition_keys": [],
            "dependent_actions": []
        },
        ...
        {
            "action": "s3:GetObjectAcl",
            "description": "Grants permission to return the access control list (ACL) of an object",
            "access_level": "Read",
            "api_documentation_link": "https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectAcl.html",
            "resource_arn_format": "arn:${Partition}:s3:::${BucketName}/${ObjectName}",
            "condition_keys": [],
            "dependent_actions": []
        },
        ...
}
```

Normally, I use something like `policy_sentry query action-table -s s3 | grep "s3:List*"` to see what permissions I give when using stars in my policies. But occasionally, I just need a little more information than just a plain text list.

## What gif best describes this PR or how it makes you feel?

Just making a little adjustment. Bones.

## Completion checklist

- [x] Additions and changes have unit tests
- [ ] [Unit tests, Pylint, security testing, and Integration tests are passing.](https://github.com/salesforce/policy_sentry/actions). GitHub actions does this automatically
- [ ] The pull request has been appropriately labeled using the provided PR labels

Let me know if more tests are needed.

### CODE REVIEW

**Comment by Scribbd** [comment]
It looks like I am failing on a workflow that is using python 3.8. Is this intended and should I reimplement the change that is compatible with the eol python 3.8?

**Comment by gruebel** [comment]
let's wait till end of this month. then I will do a new release with an updated DB. After that I will remove Python 3.8 support.

**Comment by gruebel** [comment]
@Scribbd Ok, I dropped Python 3.8. So, feel free to rebase your PR.

**Review by gruebel — APPROVED** [review]
thanks, looks good :beers:

**Pull request merged**
