### PR TITLE
[WIP] Travis Integration

### PR DESCRIPTION
**Pull request by mattyjones**
#13 

Travis is hooked up to my fork to build on pushes and pull requests. When this gets merged we should keep it this way but we set a trigger for building packages so that not every PR or push is a new package.

The nose tests are failing both locally and in Travis with an error about opening the SQLite DB I am looking at it and will figure it out in this pr.

### CODE REVIEW

**Comment by kmcquade** [comment]
@mattyjones you need to run the `initialize` command first.

**Comment by mattyjones** [comment]
@kmcquade I am going to update the [wiki](https://github.com/salesforce/policy_sentry/wiki/Developer-Guide) then as well as all it lists is `nosetests -v`

**Comment by mattyjones** [comment]
@kmcquade What are your thoughts on using [invoke](http://www.pyinvoke.org/) as a runner for testing and such?

I am thinking that because as part of this I would like to bring in linting and also security scanning via bandit. Using invoke, we could streamline and reduce the overhead of scripts needed. Think of it as something like
```
invoke test lint
invoke test vulnerability
invoke test unit
```

We could use it for other things as the project evolves as well. Just a thought, I have used it to huge effect when working with Ansible and molecule, also Rake (Ruby) in many similar projects.

**Comment by mattyjones** [comment]
@kmcquade Gonna have to think on this a little because in order to initialize you need to install it. We need to find a sane way to setup a dev environment w/o having to install it as a package. This will include running an initialize. We could just install it from the master branch but that does not currently work for me and you can't just run it due to path issues with the imports.

**Comment by mattyjones** [comment]
I am pairing this with #27 as having a proper dev environment will make Travis much easier to manage.

**Comment by kmcquade** [comment]
Cool sounds good man. Just don’t merge any of this stuff until I get back from my trip, so we can have a coordinated approach (and so I can update you on anything you missed while you were out).

But, feel free to go nuts with the PRs. Maybe merge to a different branch dedicated to your desired/proposed target state that we can go over when I’m back? I will be back Nov 11th

**Comment by xen0l** [comment]
With Travis, you can restrict when upload should happen. I am using this in my project (the important are ```on:``` conditions at the end of the file): https://github.com/xen0l/aws-gate/blob/master/.travis.yml

**Comment by mattyjones** [comment]
@kmcquade lets look at getting this in shape tomorrow and merging it so I can start working on the integration tests

**Comment by mattyjones** [comment]
#50

**Pull request closed without merging**
